### ISSUE TITLE
Html is splitted by &

### ISSUE THREAD

**Issue by salos1982** [uyamazak/hc-pdf-server#106]
Hello,

I found issue in hc-pdf-server. If HTML contains symbol `&` e.g. `&nbsp;` HTML is spliited on this symbol and part of HTML is not used for printing to PDF. 
From my point of view, it would be better if the post body will be the entire HTML. And pdf_option can be a query parameter.
Another possible solution is to encode html parameter both on a client and the server.

**Comment by uyamazak** [comment]
@salos1982 
Thank you for your issue and your views!
I could reproduce it, below code.

```
$ yarn dev
```
```
$ curl -sS http://localhost:8080 -v \
  -d html="<html><p>hcpdf <strong>ok & </strong></p><p>not show</p></html>"\
  -o hcpdf-post.pdf
```

I will consider how to fix this.
I also thought that the current specification is easier to use from normal HTML form tag with method post.
I may have left some settings out in the Fastify plugin.

**Comment by uyamazak** [comment]
When sending with a basic HTML Form like below, there was no problem because `html` was encoded.
![hc-pdf-server-test-form](https://user-images.githubusercontent.com/22805530/107322500-f0826880-6ae7-11eb-9c11-669435b9ca62.png)

Form code
```app.ts
  server.get('/testform', (_, reply) => {
    reply.type('text/html')
    reply.send(`<html>
    <title>hc-pdf-server test form</title>
    <form method="post" action="/">
      <input type="text" name="pdf_option" value="A3L">
      <textarea name="html"></textarea>
      <input type="submit" value="submit"></input>
    </form>
    </html>
    `)
  })
```


PDF
<img width="1052" alt="スクリーンショット 2021-02-09 15 07 18" src="https://user-images.githubusercontent.com/22805530/107322812-88805200-6ae8-11eb-8ad4-574b09a86901.png">

And there seems to be no problem with curl if use --data-urlencode.

```
curl -sS http://localhost:8080 -v \
  --data-urlencode html="<html><p>hcpdf <strong>ok</strong></p><p>A & B&nbsp;&amp; C OK</p></html>"\
  --data pdf_option=A3L \
  -o hcpdf-post-andA3L.pdf
```

[hcpdf-post-andA3L.pdf](https://github.com/uyamazak/hc-pdf-server/files/5949263/hcpdf-post-andA3L.pdf)

Based on the above, I thought there would be no problem if only the client side encoded `html` before sending, just like basic HTML Form.
The server side doesn't seem to need change, so just updating README.md would be good, I thought, what do you think?

**Comment by salos1982** [comment]
Yes your solution is ok

**Comment by uyamazak** [comment]
Thank you, I will update README.
